name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "develop" ]

env:
  REGION: europe-west1
  APP_NAME: szut-software
  STAGE: develop

jobs:
  deploy:
    environment: develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Tag in evn variable
        env:
          GCP_PROJECT_ID: ${{  secrets.GCP_PROJECT_ID  }}
        run: |
          echo "${{ env.APP_NAME }}-${{ env.STAGE }}" > APP_NAME_WITH_STAGE
          echo "${{ env.REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/$(cat APP_NAME_WITH_STAGE)" > REPOSITORY_URL
          echo "$(cat REPOSITORY_URL)/${{  env.APP_NAME  }}" > IMAGE_URL

      - name: Build
        run: |
          docker build -t $(cat IMAGE_URL):$GITHUB_SHA .

      - name: Tag the image to latest
        run: |
          docker tag $(cat IMAGE_URL):$GITHUB_SHA $(cat IMAGE_URL):latest

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          token_format: access_token

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Push
        run: |
          docker push "$(cat IMAGE_URL):latest"

      - name: Deploy
        run: |
          gcloud run deploy $(cat APP_NAME_WITH_STAGE) \
          --region ${{ env.REGION }} \
          --image $(cat IMAGE_URL) \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
